query ExampleQuery1 {
  getAllMovies {
    id
    title
    plotSummary
    mpaaRating
    releaseYear
    ratingPercent
    runtimeInSeconds
    crew {
      id
      job 
      person {
        id
        firstName
        lastName
      }
    }
    cast {
      id
      firstName
      lastName
      job
      person {
        birthdaySerialized
        firstName
        lastName
      }
    }
  }
}
